[package]
name = "o1"
version = "0.0.1-alpha.1"
edition = "2021"

[features]
_slow-tests = []

[dependencies]

[dev-dependencies]
rand = "~0.9.0"
rand_chacha = "~0.9.0"
ndarray = "~0.16.1"
num-traits = "~0.2.19"
statrs = "~0.18.0"
