# https://taskfile.dev
version: '3'

includes:
  o1_testing: ./o1_testing
tasks:
  test:
    env:
      RUST_BACKTRACE: full
    cmds:
      - cargo test --features _slow-tests
  lint:
    cmds:
      - pre-commit run --all
  generate:
    deps:
      - task: o1_testing:generate
