# https://taskfile.dev
version: '3'

tasks:
  test:
    env:
      RUST_BACKTRACE: full
    cmds:
      - cargo test --features _slow-tests
  lint:
    cmds:
      - pre-commit run --all
  generate:
    sources:
      - src/testing/data.rs.tpl
      - scripts/gen_map_test_data.py
    generates:
      - src/testing/data.rs
    cmds:
      - python3 scripts/gen_map_test_data.py |
        gomplate -d data=stdin:///data.json?type=application/json -f src/testing/data.rs.tpl -o src/testing/data.rs
