[package]
name = "o1_testing"
version.workspace = true
edition.workspace = true
publish = false

[dependencies]
o1_core.workspace = true
rand.workspace = true
compose-idents.workspace = true
ndarray = "~0.16.1"
num-traits = "~0.2.19"
statrs = "~0.18.0"

[lints]
workspace = true
